🐞 App Domain is properly instantiated as an array
App Domains must be [instantiated as an
array](https://github.com/cloudfoundry/capi-release/blob/fd6e68509c25d2f6732646b6e7c3dd172ed35126/jobs/cloud_controller_ng/spec#L267-L268)
in the BOSH deployment manifest, not as a string. This commit modifies
the manifest operations file to appropriately replace the system domain
with an app domain to which users can push apps/create routes. This
fixes a failure during deployment while rendering `cloud_controller_ng`
job templates.

[An important aspect of app domains is to remove the remove the ability
of users to create [routes on the system
domain](https://lists.cloudfoundry.org/g/cf-dev/topic/6333227). For
example, a user could create a route `login.system-domain` and intercept
a portion of the traffic destined for UAA.]

We took this opportunity to singularize `app_domains` → `app_domain`:

- `system_domain` is also singular
- simplifies variable instantion: `bosh deploy ... -v app_domain=foundry.fun` can be
  set on the command line; had we required an array, we would have
  needed a separate YAML file with an array of app domains
- the primary motivation, to remove `system_domain` as a location where
  users can create routes, is achieved
- additional app domains can be easily created via the CF CLI's command,
  [`create-shared-domain`](https://cli.cloudfoundry.org/en-US/cf/create-shared-domain.html)

We singularized the filenames, too.

With one app domain, we were able to remove a now-unnecessary variable,
`smoke_test_app_domain`. We now run smoke tests on the `app_domain`
specified.

fixes:
```
bosh deploy -v app_domains=foundry.fun ...
```
```diff
-       app_domains:
-       - name: foundry.fun
-       - internal: true
-         name: apps.internal
+       app_domains: foundry.fun
```
```
Task 17304 | 12:33:19 | Preparing deployment: Rendering templates (00:00:37)
                     L Error: Unable to render instance groups for deployment. Errors are:
  - Unable to render jobs for instance group 'api'. Errors are:
    - Unable to render templates for job 'cloud_controller_ng'. Errors are:
      - Error filling in template 'cloud_controller_ng.yml.erb' (line 69: undefined method `flatten' for "foundry.fun":String)
```